### PR TITLE
Adds the ability to add Mastodon feeds to iOS

### PR DESCRIPTION
**Pull request by stuartbreckenridge**
This adds the ability to add Mastodon feeds to iOS (related to #3748)

If we are happy with this implementation, I'll work on the macOS equivalent.

### CODE REVIEW

**Comment by vincode-io** [comment]
Why is this UI so very different than the other 4 options we have to add items?

**Comment by stuartbreckenridge** [comment]
Visually, it's more inline with Add Account UI. 

It's doing more than standard Add Feed UI, given the federated nature of Mastodon. 

We need username and instance. To get that we could just ask for the full URL from the user and append `.rss` and see if it's correct. But I felt splitting out username and instance was a better approach. 

For following tags, the UI doesn't give an option for the instance on which to follow the tags (which I actually think I need to correct).

**Comment by vincode-io** [comment]
It does look like an Add Account UI, but nothing like any thing else under the plus button. None of the other items there have logos or banners or explanation blocks at the bottom.

The Add Reddit Feed and Add Twitter Feed do just as much as the Add Mastodon Feed, if not more. They are done in completely different ways though.

Shouldn't we try to make sure the NetNewsWire UI is consistent for both usability reasons and aesthetic ones?

**Comment by stuartbreckenridge** [comment]
The other option I can think of would be to utilise the Mastodon [Search API](https://docs.joinmastodon.org/methods/search/). 

If we used Mastodon.social the lookup would be limited to Mastodon.social and its _federation_.

**Comment by vincode-io** [comment]
I don't have a problem with username/tag and instance being separate fields.

The username vs. tag should be a table that pushes the next screen for the user like the Twitter and Reddit add options. We should also use the same mechanism to select the Account/Folder as all the other options currently do.

I understand if you think the Mastodon option is done better. It doesn't really matter though unless we commit to changing all the other Add options as well. Consistency in app design is very important. We don't want NetNewsWire to look like a bunch of guys that don't talk to each other. We want it to look like it was made by a cohesive team, right?

**Comment by stuartbreckenridge** [comment]
I get what you mean now that I've been noodling in these views for a few days. I'll come back to this once all the Settings stuff is squared away.

**Comment by stuartbreckenridge** [comment]
Will rework this!

**Pull request closed without merging**
